version: '3'
services:
  service:
    image: chuangoing/webonline
    build:
      context: .
      dockerfile: ChuanGoing.WebOnline/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
    container_name: webonline